name: update website content

on:
  push:
    branches: [ main ]


  workflow_dispatch:

jobs:
  triggerUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MY_SECRET }}
          repository: codegeeks-ir/codegeeks-ir
          event-type: update-content
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'